config/routes.rb
Rails.application.routes.draw do
  #serves users index.html
  root to: 'users#index'
  get '/users', to: 'users#index', as: 'users'

  #handles users signing up then viewing their profile
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show'

  #handles users signing in
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'

  #handles users logging out
  delete '/sessions', to: 'sessions#destroy'

  #serves up a list of libraries
  get '/libraries', to: 'libraries#index'

  #create new library
  get '/libraries/new', to: 'libraries#new', as: 'new_library'
  post '/libraries', to: 'libraries#create'

  #serves up a list of users to a library
  get '/users/:user_id/libraries', to: 'library_users#index', as: 'user_libraries'
  post "/libraries/:library_id/users", to: "library_users#create", as: "library_users"
end

app/models/library.rb
class Library < ActiveRecord::Base
	has_many :library_users
	has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, :last_name, :email, presence: true;
	validates :email, uniqueness: true;
	has_secure_password
	has_many :library_users
	has_many :libraries, through: :library_users

	def self.confirm(params)
		@user = User.find_by_email(params[:email])
		@user.authenticate(params[:password])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

	def index
		@libraries = Library.all
		current_user
	end

	def new
		@library = Library.new
	end

	def create
		libraryParams = params.require(:library).permit(:name, :floor_count, :floor_area)
		@library = Library.create(libraryParams)

		redirect_to '/libraries'
	end

end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController

	def index
		@user = User.find(params[:user_id])
		@libraries = @user.libraries
	end

	def create
		@user = current_user
		@library = Library.find(params[:library_id])
		@user.libraries << @library

		redirect_to user_libraries_path(@user)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
		# binding.pry
	end

	def create
		user_params = params.require(:user).permit(:email, :password)
		@user = User.confirm(user_params)
		if @user
			login(@user)
			redirect_to "/users/#{@user.id}"
		else
			redirect_to '/sign_in'
		end
	end

	def destroy
		@user = User.find_by_id([params[:id]])
		logout(@user) # <-- sets users session.id to nill
		redirect_to sign_in_path # <-- redirects to sign in page
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in?, only: :show

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		userParams = params.require(:user).permit(:first_name, :last_name, :email, :password)
		@user = User.create(userParams)
		login(@user) # <-- logs in the user
		redirect_to "/users/#{@user.id}" # <-- goes to show page of that user 
	end

	def show
		# unless logged_in?
		# 	flash[:error] = "You must be logged in to access this section"
		# 	redirect_to sign_in_path
		# end
		@user = User.find(params[:id])
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end

	def current_user
		@current_user ||= User.find(session[:user_id])
	end

	def logged_in?
		if @current_user == nil
			redirect_to sign_in_path
			# binding.pry
		end
		
	end

	def logout(user)
		@current_user = session[:user_id] = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/libraries/index.html.erb
<h1>Libraries</h1>
<% @libraries.each do |library| %>
<div>
	<h3><%= library.name %></h3>
	<% if @current_user %>
		<%= button_to 'Join', library_users_path(library) %>
	<% end %>			
</div>
<br>
<% end %>

app/views/libraries/new.html.erb
<%= form_for @library do |f| %>
<%= f.text_field :name, placeholder: 'Name' %>
<%= f.text_field :floor_count, placeholder: 'Floor Count' %>
<%= f.text_field :floor_area, placeholder: 'Floor Area' %>
<%= f.submit %>
<% end %>

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries: </div>

<ul>
	<% @libraries.each do |lib| %>
	<li><%= lib.name %></li>
	<% end %>
</ul>

app/views/users/index.html.erb
<h1>Welcome</h1>

<p>There are currently <%= @users.length %> users signed up!</p>

app/views/users/new.html.erb
Sign Up

<%= form_for @user do |f| %>
	<div>
		<%= f.text_field :first_name, placeholder: 'First Name' %>
	</div>
	<div>
		<%= f.text_field :last_name, placeholder: 'Last Name' %>
	</div>
	<div>
		<%= f.text_field :email, placeholder: 'Email' %>
	</div>
	<div>
    <%= f.password_field :password, placeholder: "Password" %>
  	</div>
	<div>
		<%= f.submit 'Sign Up' %>
	</div>

<% end %>

app/views/users/show.html.erb
<div>
	Welcome, <%= @user.email %>
</div>

<%= link_to('Logout', sessions_path, method: :delete) %>